### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by dewyatt**
I had issues running older versions of paneron and ended up using master @ bfe9bfe (nice short SHA), so you may or may not want to hold off on merging.
I can at least gather feedback.

I couldn't find a working hyperlink function in paneron so the link to github is lame plain text. Any workaround on that would be helpful.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @dewyatt ! Let's merge this first.

P.S. Ping @strogonoff on Paneron hyperlinks.

**Comment by ronaldtse** [comment]
BTW @dewyatt Paneron does not natively support PRs, it would be easier to directly edit them on master through the Paneron app.

**Comment by ronaldtse** [comment]
@dewyatt To make a link in Paneron:

1. Highlight the word to link
Screen Shot 2021-01-04 at 10 17 45 AM

2. Click the "link" icon
Screen Shot 2021-01-04 at 10 18 02 AM

3. Click on the newly made link, and enter the link in the popup
Screen Shot 2021-01-04 at 10 18 12 AM

**Comment by dewyatt** [comment]
> BTW @dewyatt Paneron does not natively support PRs, it would be easier to directly edit them on master through the Paneron app.

Ok I can do that in the future, I was mostly hesitant on migrating the format without warning.

**Comment by dewyatt** [comment]
> @dewyatt To make a link in Paneron:
> 
> 1. Highlight the word to link
> 
> Screen Shot 2021-01-04 at 10 17 45 AM
> 
> 1. Click the "link" icon
> 
> Screen Shot 2021-01-04 at 10 18 02 AM
> 
> 1. Click on the newly made link, and enter the link in the popup
> 
> Screen Shot 2021-01-04 at 10 18 12 AM

That's strange, I know I did exactly these steps before and it only partially worked. Seems OK now, maybe I was toying with an older version or something, I'm not sure.

**Comment by dewyatt** [comment]
> > BTW @dewyatt Paneron does not natively support PRs, it would be easier to directly edit them on master through the Paneron app.
> 
> Ok I can do that in the future, I was mostly hesitant on migrating the format without warning.

Should I just do this and close this PR actually? Is that easier?

**Comment by ronaldtse** [comment]
Let's merge it first, there's no need to re-do!

**Comment by dewyatt** [comment]
Is there a reason that migrating to the new format in paneron drops the CI workflow?

**Comment by ronaldtse** [comment]
@dewyatt yes this is a feature in implementation: was present but it's a regression right now, tracked here: https://github.com/aperis-docs/react-static-plugin-aperis-doc-pages/issues/3.

**Pull request merged**
